In [1]:
#Import Libraries
import tensorflow as tf
from matplotlib import pyplot as plt
import cv2

#Importing Layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D,Dropout,Flatten,MaxPooling2D

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import ImageDataGenerator

import numpy as np
import matplotlib.pyplot as plt
import os

2023-01-25 11:49:51.210672: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-25 11:49:51.780148: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-01-25 11:49:51.780201: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-01-25 11:49:53.983322: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-

In [2]:
#dir_paths  
train_dir = "/home/fansan/Desktop/Document-Classifier/Dataset/data/train/"
test_dir = "/home/fansan/Desktop/Document-Classifier/Dataset/data/test/"
valid_dir="/home/fansan/Desktop/Document-Classifier/Dataset/data/valid/"
CATEGORIES = ["aadhaar", "dl", "pan", "voter"]

e='''aadhaar_dir=os.path.join(train_dir,CATEGORIES[0])
dl_dir=os.path.join(train_dir,CATEGORIES[1])
pan_dir=os.path.join(train_dir,CATEGORIES[2])
voter_dir=os.path.join(train_dir,CATEGORIES[3])

aadhaar_list=os.listdir(aadhaar_dir)
dl_list=os.listdir(dl_dir)
pan_list=os.listdir(pan_dir)
voter_list=os.listdir(voter_dir)'''

In [5]:
x_train=[]

for folder in os.listdir(train_dir):
    sub_dir=train_dir+"/"+folder
    for img in os.listdir(sub_dir):
        image_dir=sub_dir+"/"+img
        img_arr=cv2.imread(image_dir)
        img_arr=cv2.resize(img_arr,(224,224))
        x_train.append(img_arr)

x_test=[]

for folder in os.listdir(test_dir):
    sub_dir=test_dir+"/"+folder
    for img in os.listdir(sub_dir):
        image_dir=sub_dir+"/"+img
        img_arr=cv2.imread(image_dir)
        img_arr=cv2.resize(img_arr,(224,224))
        x_test.append(img_arr)

x_valid=[]

for folder in os.listdir(valid_dir):
    sub_dir=valid_dir+"/"+folder
    for img in os.listdir(sub_dir):
        image_dir=sub_dir+"/"+img
        img_arr=cv2.imread(image_dir)
        img_arr=cv2.resize(img_arr,(224,224))
        x_valid.append(img_arr)



In [6]:
train_x=np.array(x_train)
test_x=np.array(x_test)
valid_x=np.array(x_valid)

In [7]:
train_x

array([[[[ 85, 105, 176],
         [ 84, 104, 175],
         [ 81, 101, 172],
         ...,
         [ 15,  43,  51],
         [ 17,  44,  57],
         [ 21,  49,  66]],

        [[ 85, 105, 176],
         [ 83, 103, 174],
         [ 81, 101, 172],
         ...,
         [ 18,  44,  53],
         [ 20,  47,  60],
         [ 24,  53,  68]],

        [[ 84, 105, 174],
         [ 83, 103, 173],
         [ 80, 100, 170],
         ...,
         [ 21,  46,  54],
         [ 24,  51,  63],
         [ 30,  57,  72]],

        ...,

        [[ 12,  18,  63],
         [ 49,  59, 102],
         [ 85,  95, 139],
         ...,
         [  3,  12,  45],
         [  3,  12,  45],
         [  3,  12,  45]],

        [[  0,   6,  52],
         [  3,  10,  55],
         [ 16,  26,  71],
         ...,
         [  3,  12,  45],
         [  3,  12,  45],
         [  3,  12,  45]],

        [[  1,  10,  57],
         [  0,   1,  48],
         [  3,  11,  58],
         ...,
         [  3,  12,  45],
        

In [8]:
train_x=train_x/255.0
test_x=test_x/255.0
valid_x=valid_x/255.0


In [ ]:
train_x=train_x.tolist()
test_x=test_x.tolist()
valid_x=valid_x.tolist()

In [21]:
training_set = train_datagen.flow_from_directory(train_dir,
                                                 target_size = (224, 224),
                                                 batch_size = 32,
                                                 class_mode = 'sparse')
test_set = test_datagen.flow_from_directory(test_dir,
                                            target_size = (224, 224),
                                            batch_size = 32,
                                            class_mode = 'sparse')
valid_set = valid_datagen.flow_from_directory(valid_dir,
                                            target_size = (224, 224),
                                            batch_size = 32,
                                            class_mode = 'sparse')


NameError: name 'train_datagen' is not defined

In [8]:

a='''
train_generator=train_datagen.flow_from_directory(
    train_dir,
    target_size=(150,150),
    batch_size=32,
    class_mode='binary'
)
test_generator=test_datagen.flow_from_directory(
    test_dir,
    target_size=(150,150),
    batch_size=32,
    class_mode='binary'
)
valid_generator=train_datagen.flow_from_directory(
    valid_dir,
    target_size=(150,150),
    batch_size=32,
    class_mode='binary'
)'''

In [9]:
training_set.class_indices


{'aadhaar': 0, 'dl': 1, 'pan': 2, 'voter': 3}

In [10]:
train_y=training_set.classes
test_y=test_set.classes
valid_y=valid_set.classes

In [11]:
train_y=train_y.tolist()
test_y=test_y.tolist()
valid_y=valid_y.tolist()

In [12]:
train_y.shape,test_y.shape,valid_y.shape

AttributeError: 'list' object has no attribute 'shape'

In [13]:
e='''model=Sequential()
model.add(Conv2D(32,(3,3),padding='SAME',activation='relu',input_shape=(224,224,3)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.5))

model.add(Conv2D(64,(3,3),padding='SAME',activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.5))

model.add(Flatten())

model.add(Dense(256,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1,activation='sigmoid'))
model.summary()
'''


In [14]:
input_shape=(224, 224,3)
'''model=Sequential()
#model.add(Conv2D(64,kernel_size=(3,3),input_shape=input_shape))
model.add(Conv2D(32,(3,3),padding='SAME',activation='relu',input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(256,activation=tf.nn.relu))
model.add(Dropout(0.5))
model.add(Dense(10,activation=tf.nn.softmax))'''

model=Sequential()
model.add(Conv2D(28,kernel_size=(3,3),input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(128,activation=tf.nn.relu))
model.add(Dropout(0.1))
model.add(Dense(10,activation=tf.nn.softmax))
model.summary()

2023-01-22 13:11:07.551196: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-22 13:11:07.552679: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 222, 222, 28)      784       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 111, 111, 28)     0         
 )                                                               
                                                                 
 flatten (Flatten)           (None, 344988)            0         
                                                                 
 dense (Dense)               (None, 128)               44158592  
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                        

In [15]:
#model.compile(Adam(lr=0.001),loss='binary_crossentropy',metrics=['accuracy'])  
model.compile(
  loss='sparse_categorical_crossentropy',
  optimizer="adam",
  metrics=['accuracy']
)

In [16]:

history=model.fit(
    np.array(train_x),
    np.array(train_y),
    validation_data=(valid_x,valid_y),
    epochs=30,
)

#history=model.fit(training_set,
#                  epochs=30,
#                  validation_data=valid_set
#)


Epoch 1/30
1/1 [==============================] - 3s 3s/step - loss: 1.8888 - accuracy: 0.3500 - val_loss: 82.4114 - val_accuracy: 0.2000
Epoch 2/30
1/1 [==============================] - 1s 509ms/step - loss: 51.0495 - accuracy: 0.4500 - val_loss: 97.0384 - val_accuracy: 0.4000
Epoch 3/30
1/1 [==============================] - 1s 541ms/step - loss: 106.6549 - accuracy: 0.3000 - val_loss: 90.0215 - val_accuracy: 0.2000
Epoch 4/30
1/1 [==============================] - 1s 503ms/step - loss: 81.9613 - accuracy: 0.1500 - val_loss: 53.5819 - val_accuracy: 0.2000
Epoch 5/30
1/1 [==============================] - 1s 550ms/step - loss: 37.9833 - accuracy: 0.4500 - val_loss: 96.2616 - val_accuracy: 0.2000
Epoch 6/30
1/1 [==============================] - 1s 506ms/step - loss: 46.4203 - accuracy: 0.5000 - val_loss: 66.3439 - val_accuracy: 0.2000
Epoch 7/30
1/1 [==============================] - 1s 519ms/step - loss: 34.6235 - accuracy: 0.4500 - val_loss: 44.7248 - val_accuracy: 0.6000
Epoch 8/3

In [17]:
model.save('doc_datamodel.h5')

In [1]:
import cv2
from tensorflow.keras.models import load_model
from tensorflow.keras.utils import load_img,img_to_array
import numpy as np

model=load_model('doc_datamodel.h5')
img_width,img_height=150,150

2023-01-22 13:11:54.990346: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-22 13:11:57.841750: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-22 13:11:57.845811: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [2]:
pred_img="/home/fansan/Desktop/Document-Classifier/testing/test1.jpg"
prediction=model.predict(pred_img)
print(prediction)

IndexError: tuple index out of range

In [ ]:
model.predict()

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
[[[ 49  44  45]
  [ 69  64  65]
  [ 90  88  88]
  ...
  [210 221 225]
  [214 225 229]
  [214 225 229]]

 [[ 50  45  46]
  [ 69  64  65]
  [ 90  88  88]
  ...
  [210 221 225]
  [214 225 229]
  [214 225 229]]

 [[ 50  45  46]
  [ 70  65  66]
  [ 91  89  89]
  ...
  [210 221 225]
  [213 224 228]
  [214 225 229]]

 ...

 [[108 100 101]
  [123 115 116]
  [144 136 137]
  ..

[[[253 254 252]
  [253 254 252]
  [254 255 253]
  ...
  [249 253 254]
  [249 253 254]
  [249 253 254]]

 [[253 254 252]
  [253 254 252]
  [254 255 253]
  ...
  [250 254 255]
  [250 254 255]
  [250 254 255]]

 [[253 254 252]
  [254 255 253]
  [254 255 253]
  ...
  [250 254 255]
  [250 254 255]
  [251 255 255]]

 ...

 [[252 253 249]
  [252 253 249]
  [253 254 250]
  ...
  [253 255 252]
  [253 255 252]
  [252 255 251]]

 [[255 254 250]
  [255 254 250]
  [252 253 249]
  ...
  [251 255 254]
  [251 255 254]
  [251 255 254]]

 [[255 254 250]
  [255 254 250]
  [252 253 249]
  ...
  [251 255 254]
  [251 255 254]
  [251 255 254]]]
[[[148 155 164]
  [160 167 176]
  [170 179 188]
  ...
  [255 255 222]
  [255 255 234]
  [255 255 233]]

 [[153 157 168]
  [160 166 177]
  [170 176 187]
  ...
  [237 231 194]
  [253 251 220]
  [255 255 231]]

 [[181 181 199]
  [182 184 202]
  [183 185 203]
  ...
  [209 197 161]
  [233 224 191]
  [255 251 221]]

 ...

 [[132 131 140]
  [ 96  98 106]
  [ 95  95 107]
  ..

[[[241 241 241]
  [239 239 239]
  [247 247 247]
  ...
  [248 248 248]
  [248 248 248]
  [248 248 248]]

 [[241 241 241]
  [238 238 238]
  [248 248 248]
  ...
  [248 248 248]
  [248 248 248]
  [248 248 248]]

 [[247 247 247]
  [245 245 245]
  [248 248 248]
  ...
  [248 248 248]
  [248 248 248]
  [248 248 248]]

 ...

 [[228 228 228]
  [226 226 226]
  [229 229 229]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]

 [[232 232 232]
  [231 231 231]
  [232 232 232]
  ...
  [248 248 248]
  [248 248 248]
  [248 248 248]]

 [[235 235 235]
  [235 235 235]
  [238 238 238]
  ...
  [246 246 246]
  [246 246 246]
  [246 246 246]]]
[[[250 250 250]
  [252 252 252]
  [252 252 252]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[245 245 245]
  [241 241 241]
  [238 238 238]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[234 234 234]
  [225 225 225]
  [218 218 218]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
[[[ 44  37  50]
  [ 41  37  49]
  [ 44  40  52]
  ...
  [121 120 130]
  [126 125 135]
  [128 130 138]]

 [[ 43  36  49]
  [ 42  38  50]
  [ 43  41  53]
  ...
  [ 90  89  99]
  [ 90  89  98]
  [ 86  88  96]]

 [[ 43  39  50]
  [ 44  43  53]
  [ 48  47  57]
  ...
  [ 95  94 103]
  [ 98  97 106]
  [ 95  97 105]]

 ...

 [[ 18  28  28]
  [ 19  29  29]
  [ 19  27  27]
  ..

[[[ 0  1 15]
  [ 0  1 15]
  [ 0  1 15]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  1 15]
  [ 0  1 15]
  [ 0  1 15]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  1 16]
  [ 0  1 16]
  [ 0  1 16]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 ...

 [[ 0  5  8]
  [ 0  5  8]
  [ 0  5  8]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  5  8]
  [ 0  5  8]
  [ 0  5  8]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  5  8]
  [ 0  5  8]
  [ 0  5  8]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]]
[[[ 43  40  36]
  [ 78  75  71]
  [ 72  70  69]
  ...
  [ 75  74  76]
  [ 91  91  91]
  [  9   9   9]]

 [[ 93  90  86]
  [238 235 231]
  [235 233 232]
  ...
  [250 249 251]
  [214 214 214]
  [ 69  69  69]]

 [[ 72  69  65]
  [242 239 235]
  [233 231 230]
  ...
  [241 241 241]
  [204 204 204]
  [ 43  43  43]]

 ...

 [[ 77  75  75]
  [254 252 252]
  [213 213 213]
  ...
  [223 223 223]
  [223 223 223]
  [ 34  34  34]]

 [[ 85  85  85]
  [217 217 217]
  [238 238 238]
  ...
  

[[[143 159 158]
  [144 160 159]
  [145 161 160]
  ...
  [174 190 196]
  [174 190 196]
  [174 190 196]]

 [[141 157 156]
  [142 158 157]
  [143 159 158]
  ...
  [175 191 197]
  [174 190 196]
  [174 190 196]]

 [[141 157 156]
  [141 157 156]
  [143 159 158]
  ...
  [175 191 197]
  [174 190 196]
  [174 190 196]]

 ...

 [[ 84 108 114]
  [ 87 111 117]
  [ 90 114 120]
  ...
  [106 114 127]
  [106 114 127]
  [106 114 127]]

 [[ 82 106 112]
  [ 83 107 113]
  [ 84 108 114]
  ...
  [112 120 133]
  [112 120 133]
  [111 119 132]]

 [[ 85 109 115]
  [ 84 108 114]
  [ 83 107 113]
  ...
  [110 118 131]
  [108 116 129]
  [106 114 127]]]
[[[163 186 212]
  [162 185 211]
  [162 185 211]
  ...
  [ 27  39  41]
  [ 29  39  39]
  [ 29  39  39]]

 [[162 185 211]
  [162 185 211]
  [161 184 210]
  ...
  [ 27  39  41]
  [ 29  39  39]
  [ 29  39  39]]

 [[163 184 211]
  [163 184 211]
  [161 184 210]
  ...
  [ 26  39  41]
  [ 27  39  39]
  [ 27  39  39]]

 ...

 [[ 20  17  26]
  [ 59  58  67]
  [ 27  24  33]
  ..

[[[ 89  85  90]
  [ 92  88  93]
  [ 73  69  74]
  ...
  [ 59  68  88]
  [ 61  70  90]
  [ 61  70  90]]

 [[ 95  91  96]
  [ 91  87  92]
  [ 76  72  77]
  ...
  [ 26  35  55]
  [ 45  54  74]
  [ 60  69  89]]

 [[123 119 124]
  [123 119 124]
  [100  96 101]
  ...
  [ 61  70  90]
  [ 62  71  91]
  [ 50  59  79]]

 ...

 [[ 72  60  58]
  [ 72  60  58]
  [ 72  60  58]
  ...
  [ 37  44  63]
  [ 35  42  61]
  [ 35  42  61]]

 [[ 74  62  60]
  [ 73  61  59]
  [ 72  60  58]
  ...
  [ 41  48  68]
  [ 38  45  65]
  [ 35  42  62]]

 [[ 75  63  61]
  [ 74  62  60]
  [ 72  60  58]
  ...
  [ 47  54  74]
  [ 48  55  75]
  [ 45  52  72]]]
[[[255 255 255]
  [250 250 250]
  [241 241 241]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[254 254 254]
  [249 249 249]
  [238 238 238]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [249 249 249]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[248 248 248]
  [248 248 248]
  [248 248 248]
  ..

[[[211 213 214]
  [212 214 215]
  [213 215 216]
  ...
  [197 204 207]
  [197 204 207]
  [197 204 207]]

 [[211 213 214]
  [212 214 215]
  [213 215 216]
  ...
  [197 204 207]
  [197 204 207]
  [197 204 207]]

 [[211 213 214]
  [213 215 216]
  [214 216 217]
  ...
  [197 204 207]
  [197 204 207]
  [197 204 207]]

 ...

 [[192 192 192]
  [192 192 192]
  [192 192 192]
  ...
  [ 61  80 101]
  [ 63  82 103]
  [ 65  84 105]]

 [[192 192 192]
  [192 192 192]
  [192 192 192]
  ...
  [ 83 104 119]
  [ 85 106 121]
  [ 86 107 122]]

 [[191 191 191]
  [191 191 191]
  [191 191 191]
  ...
  [ 88 110 122]
  [ 88 110 122]
  [ 89 111 123]]]
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[222 222 222]
  [216 216 216]
  [234 234 234]
  ..