In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
#min dimensions
a =np.array([1,2,3,4,5],ndmin=2)
print(a)     
a  

[[1 2 3 4 5]]


array([[1, 2, 3, 4, 5]])

In [8]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a=np.array([1,2,3],dtype=complex)
print(a)


[1.+0.j 2.+0.j 3.+0.j]
[1 2 3]
