In [2]:
import numpy as np

In [11]:
#ndarray.shape
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [24]:
#reshaping
a=np.array([[1,2,3],[4,5,6]])
a.shape=(6,1)
print(a)
b=a.reshape(2,1,3,)
print(b)



[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[[1 2 3]]

 [[4 5 6]]]


In [25]:
#ndarray.ndim
a=np.arange(24)
print(a)
print(a.ndim)
b=a.reshape(2,4,3)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [31]:
x=np.array([1,2,3,4,5,6],dtype=np.int64)
print(x)
print(x.itemsize)

[1 2 3 4 5 6]
8
