In [1]:
import numpy as np

In [4]:
P=np.array([[1,7],[2,1],[3,2]])
print(P)


[[1 7]
 [2 1]
 [3 2]]


In [9]:
Q=np.array([[1,1],[1,-1],[1,0]])
print(Q)

[[ 1  1]
 [ 1 -1]
 [ 1  0]]


In [12]:
C1=np.add(P,Q)
C2=np.subtract(P,Q)

In [14]:
print(C1)
print(C2)

[[2 8]
 [3 0]
 [4 2]]
[[0 6]
 [1 2]
 [2 2]]


In [17]:
R=np.array([[1,3,1],[1,0,1]])
print(R)

[[1 3 1]
 [1 0 1]]


In [20]:
C3=np.dot(P,R)
print(C3)

[[8 3 8]
 [3 6 3]
 [5 9 5]]


In [28]:
dt=np.linalg.det(C3)
print(dt)

0.0


In [32]:
A=np.array([[1,2,3],[5,6,7],[8,9,0]])
dt=np.linalg.det(A)
print(dt)
inver=np.linalg.inv(A)
print(inver)

39.99999999999998
[[-1.575  0.675 -0.1  ]
 [ 1.4   -0.6    0.2  ]
 [-0.075  0.175 -0.1  ]]
